site_name: SID's

theme:
  name: material
  # custom_dir: overrides
  language: 'zh'
  icon:
    logo: material/text-box
    favicon: material/assistant
  font:
    text: Noto Sans SC
  palette:
    primary: 'deep purple'
    accent: pink
  features:
    - navigation.tabs

plugins:
  - search:
      lang: ja
  - mermaid2
  - awesome-pages
  - macros
extra_css:
  - stylesheets/font.css
  - stylesheets/extra.css
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.details
  - pymdownx.snippets:
      check_paths: true
      base_path: "docs"
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.critic:
      mode: view
  - pymdownx.betterem:
      smart_enable: none
  - pymdownx.caret:
      smart_insert: false
  - pymdownx.mark:
      smart_mark: false
  - pymdownx.tilde:
      smart_delete: false
  - pymdownx.smartsymbols
  - pymdownx.saneheaders
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.admonition
  - markdown.extensions.nl2br
  - markdown.extensions.toc:
      permalink: true
  - markdown.extensions.meta
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.progressbar
